[[plugins]]
package = "@imageengine/netlify"

  [plugins.inputs]
  deliveryAddress = "blazing-fast-pics.cdn.imgeng.in"

  [plugins.inputs.directives]
  height = 600
  width = 700
  rotate = 90
  
[build]
publish = "public"
